"""Added logins

Revision ID: b9133bab97f2
Revises: 58454f04c943
Create Date: 2025-05-14 06:35:31.841308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9133bab97f2'
down_revision = '58454f04c943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expires', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'refresh_token_expires')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'role')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
